insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'-1','ایجاد شده');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'0','موفق');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'1','پارامترهای ارسالی معتیر نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'2','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'3','دسترسی مورد نظر یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'4','نوع درخواست بافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'5','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'6','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'7','نام کاربری یا رمز عبور نادرست است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'8','کاربر به سرویس مورد نظر دسترسی ندارد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'9','توکن ارسالی معتبر نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'10','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'11','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'12','کانال مسدود شده است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'13','آی پی ارسالی معتبر نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'14','درخواستها بیشتر از حد مجاز میباشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'15','وضعیت یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'16','خطا در فراخوانی شاهکار');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'17','عدم تطابق شماهر همراه و کد ملی ارسالی شده');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'18','خطا در ارسال پیام کوتاه');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'19','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'20','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'21','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'22','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'23','نام کانال تکراری است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'24','کانال یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'25','کیف پول بافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'26','نوع واحد حساب کیف یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'27','نوع حساب کیف یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'28','نوع کیف یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'29','امضا دیجیتال نامعتبر میباشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'30','ایحاد کیف پول با خطا همراه است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'31','شناسه یکتا یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'32','شناسه یکتا تکراری است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'33','شماره مرجع تکراری میباشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'34','کیف فعال نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'35','حساب کیف یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'36','حساب کیف فعال نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'37','مبلغ کمتر از حد مجاز');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'38','تنظیمات مرتبط یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'39','کیف اجازه افزایش موجودی را ندارد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'40','مبلغ بیشتر از حد مجاز');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'41','مانده کیف بیشتر از حد مجاز است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'42','مبلغ بیشتر از حد مجاز روزانه است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'43','موجودی کافی نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'44','رکورد یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'45','پذیرنده یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'46','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'47','');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'898','رفرش توکن به کاربر متعلق نیست');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'899','رفرش توکن یافت نشد');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'900','رفرش توکن منقضی شده است');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'988','خطا در همگام سازی');
insert into status(created_by, created_at, code, persian_description) values ('admin',now(),'999','بروز خطای ناشناخته در اجرای سرویس');