package com.melli.wallet.service.repository;


import com.melli.wallet.domain.master.entity.StatusEntity;
import com.melli.wallet.exception.InternalServiceException;

public interface StatusRepositoryService {

    int CREATE = -1;
    int SUCCESSFUL = 0;
    int INPUT_PARAMETER_NOT_VALID = 1;
    int PASSWORD_NOT_MATCH = 2;
    int ROLE_NAME_NOT_FOUND = 3;
    int REQUEST_TYPE_NOT_FOUND = 4;
    int NATIONAL_CODE_NOT_FOUND = 5;
    int NATIONAL_CODE_EXIT = 6;
    int INVALID_USERNAME_PASSWORD = 7;
    int USER_NOT_PERMISSION = 8;
    int TOKEN_NOT_VALID = 9;
    int PROFILE_NOT_FOUND = 10;
    int EXPIRE_TIME_FOR_UPDATE_PASSWORD = 11;
    int CHANNEL_IS_BLOCKED = 12;
    int INVALID_IP_ADDRESS = 13;
    int TOO_MANY_REQUESTS = 14;
    int STATUS_NOT_FOUND = 15;
    int ERROR_IN_GET_SHAHKAR = 16;
    int MOBILE_AND_NATIONAL_CODE_NOT_MATCH = 17;

    int ERROR_IN_SEND_SMS = 18;
    int WALLET_EXIST_WITH_ANOTHER_MOBILE = 19;
    int TOO_MANY_OTP = 22;
    int DUPLICATE_CHANNEL_NAME = 23;
    int CHANNEL_NOT_FOUND = 24;
    int WALLET_NOT_FOUND = 25;
    int WALLET_ACCOUNT_CURRENCY_NOT_FOUND = 26;
    int WALLET_ACCOUNT_TYPE_NOT_FOUND = 27;
    int WALLET_TYPE_NOT_FOUND = 28;
    int INVALID_SIGN = 29;
    int WALLET_NOT_CREATE_SUCCESS = 30;
    int UUID_NOT_FOUND = 31;
    int DUPLICATE_UUID = 32;
    int REF_NUMBER_USED_BEFORE = 33;
    int WALLET_IS_NOT_ACTIVE = 34;
    int WALLET_ACCOUNT_NOT_FOUND = 35;
    int WALLET_ACCOUNT_IS_NOT_ACTIVE = 36;
    int AMOUNT_LESS_THAN_MIN = 37;
    int SETTING_NOT_FOUND = 38;
    int ACCOUNT_DONT_PERMISSION_FOR_CASH_IN = 39;
    int AMOUNT_BIGGER_THAN_MAX = 40;
    int BALANCE_MORE_THAN_STANDARD = 41;
    int WALLET_EXCEEDED_AMOUNT_LIMITATION = 42;
    int BALANCE_IS_NOT_ENOUGH = 43;
    int RECORD_NOT_FOUND = 44;
    int MERCHANT_IS_NOT_EXIST = 45;
    int MERCHANT_WALLET_ACCOUNT_NOT_FOUND = 46;
    int CHANNEL_WALLET_ACCOUNT_NOT_FOUND = 47;
    int SETTING_MORE_THAN_ONE_RECORD = 48;
    int LIMITATION_NAME_IS_EXIST = 49;
    int LIMITATION_NOT_FOUND = 50;
    int PRICE_NOT_SAME_WITH_UUID = 51;
    int ACCOUNT_NUMBER_NOT_SAME_WITH_UUID = 52;
    int BUY_EXCEEDED_QUANTITY_DAILY_LIMITATION = 53;
    int BUY_EXCEEDED_COUNT_DAILY_LIMITATION = 54;
    int BUY_EXCEEDED_QUANTITY_MONTHLY_LIMITATION = 55;
    int BUY_EXCEEDED_COUNT_MONTHLY_LIMITATION = 56;

    int COMMISSION_CURRENCY_NOT_VALID = 57;
    int QUANTITY_LESS_THAN_MIN = 58;
    int QUANTITY_BIGGER_THAN_MAX = 59;



    int EXCEEDED_AMOUNT_MONTHLY_LIMITATION = 60;
    int EXCEEDED_COUNT_MONTHLY_LIMITATION = 61;
    int EXCEEDED_AMOUNT_DAILY_LIMITATION = 62;
    int EXCEEDED_COUNT_DAILY_LIMITATION = 63;
    int ACCOUNT_DONT_PERMISSION_FOR_CASH_OUT = 64;
    int CASHOUT_EXCEEDED_COUNT_MONTHLY_LIMITATION = 65;
    int CASHOUT_EXCEEDED_AMOUNT_DAILY_LIMITATION = 66;
    int WALLET_LEVEL_NOT_FOUND = 67;
    int MERCHANT_BALANCE_NOT_ENOUGH = 68;


    int ACCOUNT_DONT_PERMISSION_FOR_PHYSICAL_CASH_OUT = 69;
    int PHYSICAL_CASHOUT_EXCEEDED_COUNT_MONTHLY_LIMITATION = 70;
    int PHYSICAL_CASHOUT_EXCEEDED_AMOUNT_DAILY_LIMITATION = 71;

    int MERCHANT_IS_DISABLE = 72;
    
    // Panel Role Management Status Codes
    int ROLE_NOT_FOUND = 73;
    int ROLE_ALREADY_EXISTS = 74;
    int ROLE_IN_USE = 75;
    int ROLE_ALREADY_ASSIGNED = 76;
    int ROLE_NOT_ASSIGNED = 77;
    
    // Panel Resource Management Status Codes
    int RESOURCE_NOT_FOUND = 78;
    int RESOURCE_ALREADY_EXISTS = 79;
    int RESOURCE_IN_USE = 80;
    int CHANNEL_IS_DISABLE = 81;
    int ERROR_IN_SAVE_UNIQUE_ACCOUNT_NUMBER = 82;
    int SRC_ACCOUNT_SAME_DST_ACCOUNT_NUMBER = 83;
    int CURRENCY_SRC_ACCOUNT_SAME_DST_ACCOUNT_NUMBER = 84;
    int DST_ACCOUNT_NUMBER_NOT_FOUND = 85;
    int STOCK_NOT_FOUND = 86;
    int COMMISSION_BIGGER_THAN_QUANTITY = 87;
    int GIFT_CARD_NOT_UNIQUE = 88;
    int ACCOUNT_DONT_PERMISSION_FOR_GIFT_CARD = 89;
    int GIFT_CARD_NOT_FOUND = 90;
    int NATIONAL_CODE_NOT_PERMISSION_FOR_PAYMENT_GIFT_CARD = 91;
    int GIFT_CARD_IS_EXPIRE = 92;
    int CURRENCY_NOT_MATCH_WITH_ACCOUNT = 93;
    int ACCOUNT_DONT_PERMISSION_FOR_COLLATERAL = 94;
    int COLLATERAL_CODE_NOT_FOUND = 95;
    int OWNER_COLLATERAL_CODE_SAME = 96;
    int COLLATERAL_RELEASE_BEFORE = 97;
    int COLLATERAL_QUANTITY_NOT_SAME = 98;
    int COLLATERAL_NATIONAL_CODE_NOT_SAME = 99;
    int COLLATERAL_QUANTITY_IS_BIGGER_THAN_BLOCK_QUANTITY = 100;
    int BLOCK_AMOUNT_NOT_ENOUGH = 101;
    int COLLATERAL_ACCOUNT_NOT_FOUND = 102;
    int COLLATERAL_NOT_FOUND = 103;
    int COLLATERAL_STEP_MUST_BE_SEIZE = 104;

    // General Error Codes


    int REFRESH_TOKEN_NOT_BELONG_TO_PROFILE = 898;
    int REFRESH_TOKEN_NOT_FOUND = 899;
    int REFRESH_TOKEN_IS_EXPIRE = 900;
    int ERROR_IN_LOCK = 988;
    int INTERNAL_ERROR = 997;
    int TIMEOUT = 998;
    int GENERAL_ERROR = 999;


    void init();

    StatusEntity findByCode(String code);

    void clearCache();

    StatusEntity findById(long id) throws InternalServiceException;

    StatusEntity findByPersianDescription(String persianDescription);
}
